'use server';

/**
 * @fileOverview Generates AI-driven life coaching tips for users.
 *
 * - generateAiProTip - A function to generate a single AI pro tip.
 * - GenerateAiProTipInput - The input type for the generateAiProTip function (currently empty).
 * - GenerateAiProTipOutput - The return type for the generateAiProTip function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GenerateAiProTipInputSchema = z.object({});
export type GenerateAiProTipInput = z.infer<typeof GenerateAiProTipInputSchema>;

const GenerateAiProTipOutputSchema = z.object({
  tip: z.string().describe('A life coaching tip generated by AI.'),
  additionalInfo: z.string().optional().describe('Optional additional information to enhance the pro tip.'),
});
export type GenerateAiProTipOutput = z.infer<typeof GenerateAiProTipOutputSchema>;

const provideAdditionalContext = ai.defineTool(
  {
    name: 'provideAdditionalContext',
    description: 'Decides whether to add an extra helpful context to the life coaching tip.',
    inputSchema: z.object({
      tip: z.string().describe('The generated life coaching tip.'),
    }),
    outputSchema: z.boolean().describe('Whether additional context should be added.'),
  },
  async (input) => {
    // Simulate a decision-making process; in a real app, this might involve an API call.
    return Math.random() < 0.5; // 50% chance of adding additional context.
  }
);

const aiProTipPrompt = ai.definePrompt({
  name: 'aiProTipPrompt',
  tools: [provideAdditionalContext],
  input: {schema: GenerateAiProTipInputSchema},
  output: {schema: GenerateAiProTipOutputSchema},
  prompt: `You are a life coach providing a single, actionable life coaching tip.

Generate a new life coaching tip for the user. The tip should be concise and easy to understand.

{{~#if (await provideAdditionalContext tip=(this.tip))~}}
  Also, provide an additional piece of information which can enhance the life coaching tip.
{{~/if~}}
`,
});

const generateAiProTipFlow = ai.defineFlow(
  {
    name: 'generateAiProTipFlow',
    inputSchema: GenerateAiProTipInputSchema,
    outputSchema: GenerateAiProTipOutputSchema,
  },
  async () => {
    const {output} = await aiProTipPrompt({});
    return output!;
  }
);

export async function generateAiProTip(): Promise<GenerateAiProTipOutput> {
  return generateAiProTipFlow();
}
